### ISSUE TITLE
unsupervised_class3/bayes_classifier_gmm.py

### ISSUE THREAD

**Issue by SergeKrier** [lazyprogrammer/machine_learning_examples#9]
```
python3 bayes_classifier_gmm.py
Reading in and transforming data...
Fitting gmm 0
Traceback (most recent call last):
  File "bayes_classifier_gmm.py", line 52, in <module>
    clf.fit(X, Y)
  File "bayes_classifier_gmm.py", line 23, in fit
    self.p_y[k] = len(Xk)
```

easy fix : 

```
*** bayes_classifier_gmm.py	Thu Aug  3 12:15:56 2017
--- bayes_classifier_gmm.py~	Tue Aug  1 18:33:18 2017
***************
*** 20,28 ****
      self.p_y = np.zeros(self.K)
      for k in range(self.K):
        print("Fitting gmm", k)
-       Xk = X[Y == k]
        self.p_y[k] = len(Xk)
!
        gmm = BayesianGaussianMixture(10)
        gmm.fit(Xk)
        self.gaussians.append(gmm)
--- 20,27 ----
      self.p_y = np.zeros(self.K)
      for k in range(self.K):
        print("Fitting gmm", k)
        self.p_y[k] = len(Xk)
!       Xk = X[Y == k]
        gmm = BayesianGaussianMixture(10)
        gmm.fit(Xk)
        self.gaussians.append(gmm)
```

**Comment by lazyprogrammer** [comment]
It's been fixed! That's what I get for making ad-hoc changes. =)

Thanks for mentioning!
